# Generated by Django 5.2.8 on 2025-11-28 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0004_question_difficulty'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='verse_reference',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
