# Generated by Django 5.2.8 on 2025-11-27 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyverse',
            name='content_es',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='dailyverse',
            name='reference_es',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='dailyverse',
            name='theme_es',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dailyverse',
            name='version_es',
            field=models.CharField(default='RVR1960', max_length=20),
        ),
    ]
