import type { Metadata } from "next";
import { Cormorant_Garamond } from "next/font/google";
import "./globals.css";

const CormorantGaramond = Cormorant_Garamond({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "On Wings",
  description: "Generated by create next app",
};

import { ThemeProvider } from "@/components/theme-provider";
import { NavBar } from "@/components/nav-bar";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${CormorantGaramond.className} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <NavBar />
          {children}
        </ThemeProvider>
      </body>
    </html>

  );
}
